apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books-api-staging-oci
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/parraletz/charts/books-api
      targetRevision: "5.2.1"
      chart: books-api
      path: .
      helm:
        releaseName: books-api
        valuesObject:
          ingressGateway:
            enabled: true
            hosts:
              - host: books-api.staging.cloudnative.lat
          scaleObject:
            enabled: true
            minReplicaCount: 1
            maxReplicaCount: 10
            targetCPUUtilizationPercentage: 50
            targetMemoryUtilizationPercentage: 50
          image:
            tag: "5.2.1"
            repository: ghcr.io/parraletz/books-api
            # valuesFiles:
            #   - $values/books/api/values-staging.yaml
    - repoURL: git@github.com:parraletz/gitops-cf.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: books-api-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
